import { normalizeWhitespace } from "../../exploration";
import type { ProductFlowMap, ProductFlowPage, ProductGeneratedTestCase } from "../../../types";
import { regexLiteralForText } from "../strings";

export function renderGeneratedProductTestSource(
  flowMap: ProductFlowMap,
  tests: ProductGeneratedTestCase[],
  sourceFlowMapPath: string
): string {
  const lines = [
    "import { test, expect } from '@playwright/test';",
    "",
    "// @generated by CodeDecay. Review before promoting into your permanent test suite.",
    `// codedecay:source-flow-map=${sourceFlowMapPath}`,
    `// codedecay:target=${flowMap.target.id}`,
    "",
    `const CODEDECAY_BASE_URL = process.env.CODEDECAY_PRODUCT_BASE_URL ?? ${JSON.stringify(flowMap.target.baseUrl)};`,
    "",
    "function productUrl(path: string): string {",
    "  return new URL(path, CODEDECAY_BASE_URL.endsWith('/') ? CODEDECAY_BASE_URL : `${CODEDECAY_BASE_URL}/`).toString();",
    "}",
    "",
    `test.describe(${JSON.stringify(`CodeDecay generated product regression tests (${flowMap.target.id})`)}, () => {`
  ];

  for (const testCase of tests) {
    lines.push("", `  test(${JSON.stringify(testCase.title)}, async ({ page }) => {`, `    test.info().annotations.push({ type: 'codedecay.testId', description: ${JSON.stringify(testCase.id)} });`);
    appendGeneratedTestBody(lines, testCase, flowMap);
    lines.push("  });");
  }

  lines.push("});", "");
  return lines.join("\n");
}

function appendGeneratedTestBody(lines: string[], testCase: ProductGeneratedTestCase, flowMap: ProductFlowMap): void {
  const page = findFlowPageForTest(flowMap, testCase.pageUrl);
  const pagePath = new URL(testCase.pageUrl).pathname || "/";

  if (testCase.kind === "route-load") {
    lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
    lines.push("    await expect(page.locator('body')).toBeVisible();");
    if (page?.title) {
      lines.push(`    await expect(page).toHaveTitle(${regexLiteralForText(page.title)});`);
    }
    return;
  }

  if (testCase.kind === "link-navigation") {
    const link = page?.links.find((candidate) => candidate.href === testCase.targetUrl || candidate.selector === testCase.selector);
    lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
    lines.push(`    await ${locatorForInteractiveElement("link", link?.text ?? testCase.title, testCase.selector)}.click();`);
    lines.push(`    await expect(page).toHaveURL(productUrl(${JSON.stringify(new URL(testCase.targetUrl ?? testCase.pageUrl).pathname || "/")}));`);
    return;
  }

  if (testCase.kind === "input-state") {
    const element = page?.interactiveElements.find((candidate) => candidate.selector === testCase.selector);
    const sampleValue = sampleValueForInput(element?.inputType, element?.name);
    lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
    lines.push(`    const field = ${locatorForInteractiveElement("input", element?.name ?? testCase.title, testCase.selector)};`);
    lines.push(`    await field.fill(${JSON.stringify(sampleValue)});`);
    lines.push(`    await expect(field).toHaveValue(${JSON.stringify(sampleValue)});`);
    return;
  }

  const element = page?.interactiveElements.find((candidate) => candidate.selector === testCase.selector);
  lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
  lines.push(`    await expect(${locatorForInteractiveElement("form", element?.name ?? testCase.title, testCase.selector)}).toBeVisible();`);
}

function locatorForInteractiveElement(kind: "link" | "input" | "form", name: string, selector: string | undefined): string {
  const safeName = normalizeWhitespace(name);
  const fallback = selector ? `.or(page.locator(${JSON.stringify(selector)}))` : "";
  if (kind === "link") {
    return `page.getByRole('link', { name: ${regexLiteralForText(safeName)} }).first()${fallback}`;
  }

  if (kind === "input") {
    return `page.getByLabel(${regexLiteralForText(safeName)}).or(page.getByPlaceholder(${regexLiteralForText(safeName)}))${fallback}.first()`;
  }

  return selector ? `page.locator(${JSON.stringify(selector)}).first()` : `page.getByRole('form', { name: ${regexLiteralForText(safeName)} }).first()`;
}

function findFlowPageForTest(flowMap: ProductFlowMap, url: string): ProductFlowPage | undefined {
  return flowMap.pages.find((page) => page.url === url);
}

function sampleValueForInput(inputType: string | undefined, name: string | undefined): string {
  const normalized = `${inputType ?? ""} ${name ?? ""}`.toLowerCase();
  if (normalized.includes("email")) {
    return "codedecay@example.com";
  }

  if (normalized.includes("phone") || normalized.includes("tel")) {
    return "5550100";
  }

  if (normalized.includes("url")) {
    return "https://example.com";
  }

  if (normalized.includes("password")) {
    return "CodeDecayTest123!";
  }

  return "CodeDecay test";
}
