import type { CodeDecayProductApiEndpoint } from "@submuxhq/codedecay-config";
import {
  PRODUCT_API_METHODS,
  SAFE_PRODUCT_API_METHODS,
  type OpenApiDocument,
  type OpenApiOperation,
  type OpenApiParameter,
  type OpenApiPathItem,
  type OpenApiSchema,
  type ProductHttpMethod
} from "./openapi";
import { priorityForPath, priorityRank } from "./priority";
import { generatedTestId } from "./strings";
import type { ProductGeneratedTestCase } from "../../types";

export function createGeneratedProductApiTestCases(
  document: OpenApiDocument,
  baseUrl: string,
  impactedPaths: Set<string>
): ProductGeneratedTestCase[] {
  const tests: ProductGeneratedTestCase[] = [];
  const seen = new Set<string>();
  const paths = document.paths ?? {};

  for (const path of Object.keys(paths).sort((left, right) => left.localeCompare(right))) {
    const pathItem = paths[path];
    if (!pathItem || typeof pathItem !== "object") {
      continue;
    }

    for (const method of PRODUCT_API_METHODS) {
      const operation = pathItem[method.toLowerCase() as Lowercase<ProductHttpMethod>];
      if (!operation || typeof operation !== "object") {
        continue;
      }

      const operationPath = sampleOpenApiOperationPath(path, pathItem, operation);
      const expectedStatuses = openApiExpectedStatuses(operation);
      const destructive = !SAFE_PRODUCT_API_METHODS.has(method);
      const id = generatedTestId("api", method, path, operation.operationId ?? "");
      addGeneratedTestCase(tests, seen, {
        id,
        title: `${method} ${path} returns a documented status`,
        kind: "api-operation",
        pageUrl: new URL(operationPath, baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`).toString(),
        method,
        operationPath,
        operationId: operation.operationId,
        expectedStatuses,
        requestBody: destructive ? sampleOpenApiRequestBody(operation) : undefined,
        destructive,
        priority: priorityForPath(path, impactedPaths)
      });
    }
  }

  return tests.sort((left, right) => priorityRank(left.priority) - priorityRank(right.priority) || left.id.localeCompare(right.id));
}

export function createConfiguredProductApiTestCases(
  endpoints: CodeDecayProductApiEndpoint[],
  baseUrl: string,
  impactedPaths: Set<string>
): ProductGeneratedTestCase[] {
  const tests: ProductGeneratedTestCase[] = [];
  const seen = new Set<string>();

  for (const endpoint of endpoints) {
    const destructive = !SAFE_PRODUCT_API_METHODS.has(endpoint.method);
    const id = endpoint.id ?? generatedTestId("api", "configured", endpoint.method, endpoint.path);
    addGeneratedTestCase(tests, seen, {
      id,
      title: `${endpoint.method} ${endpoint.path} returns a configured status`,
      kind: "api-operation",
      pageUrl: new URL(endpoint.path, baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`).toString(),
      method: endpoint.method,
      operationPath: endpoint.path,
      expectedStatuses: endpoint.expectedStatuses,
      headers: endpoint.headers,
      requestBody: endpoint.body,
      destructive,
      priority: priorityForPath(endpoint.path, impactedPaths)
    });
  }

  return tests.sort((left, right) => priorityRank(left.priority) - priorityRank(right.priority) || left.id.localeCompare(right.id));
}

export function renderGeneratedProductApiTestSource(
  targetId: string,
  baseUrl: string,
  sourceSchemaPath: string,
  tests: ProductGeneratedTestCase[],
  allowDestructiveActions: boolean
): string {
  const lines = [
    "import { test } from '@playwright/test';",
    "",
    "// @generated by CodeDecay. Review before promoting into your permanent test suite.",
    `// codedecay:source-openapi-schema=${sourceSchemaPath}`,
    `// codedecay:target=${targetId}`,
    "",
    `const CODEDECAY_API_BASE_URL = process.env.CODEDECAY_PRODUCT_BASE_URL ?? ${JSON.stringify(baseUrl)};`,
    "",
    "function apiUrl(path: string): string {",
    "  return new URL(path, CODEDECAY_API_BASE_URL.endsWith('/') ? CODEDECAY_API_BASE_URL : `${CODEDECAY_API_BASE_URL}/`).toString();",
    "}",
    "",
    "async function responseSnippet(response: { text: () => Promise<string> }): Promise<string> {",
    "  try {",
    "    return (await response.text()).replace(/\\s+/g, ' ').trim().slice(0, 500);",
    "  } catch {",
    "    return '';",
    "  }",
    "}",
    "",
    `test.describe(${JSON.stringify(`CodeDecay generated API regression tests (${targetId})`)}, () => {`
  ];

  for (const testCase of tests) {
    const declaration = testCase.destructive && !allowDestructiveActions ? "test.skip" : "test";
    lines.push(
      "",
      `  ${declaration}(${JSON.stringify(testCase.title)}, async ({ request }) => {`,
      `    test.info().annotations.push({ type: 'codedecay.testId', description: ${JSON.stringify(testCase.id)} });`
    );
    appendGeneratedApiTestBody(lines, testCase);
    lines.push("  });");
  }

  lines.push("});", "");
  return lines.join("\n");
}

function addGeneratedTestCase(tests: ProductGeneratedTestCase[], seen: Set<string>, test: ProductGeneratedTestCase): void {
  if (seen.has(test.id)) {
    return;
  }

  seen.add(test.id);
  tests.push(test);
}

function appendGeneratedApiTestBody(lines: string[], testCase: ProductGeneratedTestCase): void {
  const method = testCase.method ?? "GET";
  const operationPath = testCase.operationPath ?? new URL(testCase.pageUrl).pathname;
  const expectedStatuses = testCase.expectedStatuses ?? [];
  const requestBody = testCase.requestBody;
  const headers =
    requestBody === undefined
      ? { accept: "application/json", ...(testCase.headers ?? {}) }
      : { accept: "application/json", "content-type": "application/json", ...(testCase.headers ?? {}) };
  lines.push("    const response = await request.fetch(");
  lines.push(`      apiUrl(${JSON.stringify(operationPath)}),`);
  lines.push("      {");
  lines.push(`        method: ${JSON.stringify(method)},`);
  lines.push(`        headers: ${JSON.stringify(headers)}${requestBody === undefined ? "" : ","}`);
  if (requestBody !== undefined) {
    lines.push(`        data: ${JSON.stringify(requestBody, null, 10).replace(/\n/g, "\n        ")}`);
  }
  lines.push("      }");
  lines.push("    );");
  lines.push("    const status = response.status();");
  if (expectedStatuses.length > 0) {
    lines.push(`    const expectedStatuses = ${JSON.stringify(expectedStatuses)};`);
    lines.push("    if (!expectedStatuses.includes(status)) {");
    lines.push("      throw new Error(`Expected documented status ${expectedStatuses.join(', ')} but got ${status}. Body: ${await responseSnippet(response)}`);");
    lines.push("    }");
  } else {
    lines.push("    if (status >= 500) {");
    lines.push("      throw new Error(`Expected a non-5xx API response but got ${status}. Body: ${await responseSnippet(response)}`);");
    lines.push("    }");
  }
}

function sampleOpenApiRequestBody(operation: OpenApiOperation): unknown {
  const content = operation.requestBody?.content;
  const jsonMedia = content?.["application/json"] ?? content?.["application/problem+json"] ?? Object.values(content ?? {}).find(Boolean);
  if (!jsonMedia) {
    return {
      codedecay: "review-before-running"
    };
  }

  if (jsonMedia.example !== undefined) {
    return jsonMedia.example;
  }

  return sampleOpenApiSchemaValue(jsonMedia.schema);
}

function sampleOpenApiSchemaValue(schema: OpenApiSchema | undefined): unknown {
  if (!schema) {
    return {
      codedecay: "review-before-running"
    };
  }

  if (schema.example !== undefined) {
    return schema.example;
  }

  if (schema.default !== undefined) {
    return schema.default;
  }

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum[0];
  }

  if (schema.type === "array") {
    return [sampleOpenApiSchemaValue(schema.items)];
  }

  if (schema.type === "integer" || schema.type === "number") {
    return 1;
  }

  if (schema.type === "boolean") {
    return true;
  }

  if (schema.type === "string") {
    if (schema.format === "email") {
      return "codedecay@example.com";
    }

    if (schema.format === "uri" || schema.format === "url") {
      return "https://example.com";
    }

    if (schema.format === "uuid") {
      return "00000000-0000-4000-8000-000000000001";
    }

    return "codedecay";
  }

  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? Object.keys(properties));
  const value: Record<string, unknown> = {};
  for (const [name, property] of Object.entries(properties)) {
    if (!required.has(name)) {
      continue;
    }

    value[name] = sampleOpenApiSchemaValue(property);
  }

  return Object.keys(value).length > 0 ? value : { codedecay: "review-before-running" };
}

function sampleOpenApiOperationPath(path: string, pathItem: OpenApiPathItem, operation: OpenApiOperation): string {
  const parameters = [...(pathItem.parameters ?? []), ...(operation.parameters ?? [])];
  const replacedPath = path.replace(/\{([^}]+)\}/g, (_match, name: string) => encodeURIComponent(String(sampleOpenApiParameterValue(name, parameters))));
  const query = new URLSearchParams();

  for (const parameter of parameters) {
    if (parameter.in !== "query" || !parameter.name || parameter.required !== true) {
      continue;
    }

    query.set(parameter.name, String(sampleOpenApiParameterValue(parameter.name, parameters)));
  }

  const queryString = query.toString();
  return queryString ? `${replacedPath}?${queryString}` : replacedPath;
}

function sampleOpenApiParameterValue(name: string, parameters: OpenApiParameter[]): string | number | boolean {
  const parameter = parameters.find((candidate) => candidate.name === name);
  const schema = parameter?.schema;
  const lowerName = name.toLowerCase();

  if (parameter?.example !== undefined) {
    return primitiveSampleValue(parameter.example);
  }

  if (schema?.example !== undefined) {
    return primitiveSampleValue(schema.example);
  }

  if (schema?.default !== undefined) {
    return primitiveSampleValue(schema.default);
  }

  if (Array.isArray(schema?.enum) && schema.enum.length > 0) {
    return primitiveSampleValue(schema.enum[0]);
  }

  if (schema?.type === "integer" || schema?.type === "number" || /\b(id|count|page|limit|offset)\b/i.test(lowerName)) {
    return 1;
  }

  if (schema?.type === "boolean") {
    return true;
  }

  if (schema?.format === "email" || lowerName.includes("email")) {
    return "codedecay@example.com";
  }

  if (schema?.format === "uuid" || lowerName.includes("uuid")) {
    return "00000000-0000-4000-8000-000000000001";
  }

  return "codedecay";
}

function primitiveSampleValue(value: unknown): string | number | boolean {
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return value;
  }

  if (value === null || value === undefined) {
    return "codedecay";
  }

  return JSON.stringify(value);
}

function openApiExpectedStatuses(operation: OpenApiOperation): number[] {
  return Object.keys(operation.responses ?? {})
    .filter((status) => /^\d{3}$/.test(status))
    .map((status) => Number(status))
    .filter((status) => status >= 100 && status < 500)
    .sort((left, right) => left - right);
}
