import { normalizeWhitespace } from "../exploration";
import type { ProductFlowMap, ProductFlowPage, ProductGeneratedTestCase } from "../../types";
import { priorityForPath, priorityRank } from "./priority";
import { generatedTestId, regexLiteralForText } from "./strings";

export function createGeneratedProductTestCases(
  flowMap: ProductFlowMap,
  impactedPaths: Set<string>
): ProductGeneratedTestCase[] {
  const tests: ProductGeneratedTestCase[] = [];
  const pages = [...flowMap.pages].sort((left, right) => left.depth - right.depth || left.url.localeCompare(right.url));
  const seen = new Set<string>();

  for (const page of pages) {
    addGeneratedTestCase(tests, seen, {
      id: generatedTestId("route", page.path),
      title: `loads ${page.path || "/"}`,
      kind: "route-load",
      pageUrl: page.url,
      priority: priorityForPath(page.path, impactedPaths)
    });
  }

  for (const page of pages) {
    const links = page.links
      .filter((link) => link.sameOrigin && link.discovered && link.text.trim().length > 0)
      .sort((left, right) => left.href.localeCompare(right.href));

    for (const link of links) {
      addGeneratedTestCase(tests, seen, {
        id: generatedTestId("link", page.path, new URL(link.href).pathname, link.text),
        title: `navigates from ${page.path || "/"} to ${new URL(link.href).pathname || "/"} via ${link.text}`,
        kind: "link-navigation",
        pageUrl: page.url,
        selector: link.selector,
        targetUrl: link.href,
        priority: priorityForPath(new URL(link.href).pathname, impactedPaths)
      });
    }
  }

  for (const page of pages) {
    const inputs = page.interactiveElements
      .filter((element) => element.kind === "input" && !element.blocked && safeInputType(element.inputType))
      .sort((left, right) => left.selector.localeCompare(right.selector));

    for (const input of inputs) {
      addGeneratedTestCase(tests, seen, {
        id: generatedTestId("input", page.path, input.name, input.selector),
        title: `fills ${input.name} on ${page.path || "/"}`,
        kind: "input-state",
        pageUrl: page.url,
        selector: input.selector,
        priority: priorityForPath(page.path, impactedPaths)
      });
    }
  }

  for (const page of pages) {
    const forms = page.interactiveElements
      .filter((element) => element.kind === "form" && !element.blocked)
      .sort((left, right) => left.selector.localeCompare(right.selector));

    for (const form of forms) {
      addGeneratedTestCase(tests, seen, {
        id: generatedTestId("form", page.path, form.name, form.selector),
        title: `shows safe form ${form.name} on ${page.path || "/"}`,
        kind: "form-visibility",
        pageUrl: page.url,
        selector: form.selector,
        priority: priorityForPath(page.path, impactedPaths)
      });
    }
  }

  return tests.sort((left, right) => priorityRank(left.priority) - priorityRank(right.priority) || left.id.localeCompare(right.id));
}

export function renderGeneratedProductTestSource(
  flowMap: ProductFlowMap,
  tests: ProductGeneratedTestCase[],
  sourceFlowMapPath: string
): string {
  const lines = [
    "import { test, expect } from '@playwright/test';",
    "",
    "// @generated by CodeDecay. Review before promoting into your permanent test suite.",
    `// codedecay:source-flow-map=${sourceFlowMapPath}`,
    `// codedecay:target=${flowMap.target.id}`,
    "",
    `const CODEDECAY_BASE_URL = process.env.CODEDECAY_PRODUCT_BASE_URL ?? ${JSON.stringify(flowMap.target.baseUrl)};`,
    "",
    "function productUrl(path: string): string {",
    "  return new URL(path, CODEDECAY_BASE_URL.endsWith('/') ? CODEDECAY_BASE_URL : `${CODEDECAY_BASE_URL}/`).toString();",
    "}",
    "",
    `test.describe(${JSON.stringify(`CodeDecay generated product regression tests (${flowMap.target.id})`)}, () => {`
  ];

  for (const testCase of tests) {
    lines.push("", `  test(${JSON.stringify(testCase.title)}, async ({ page }) => {`, `    test.info().annotations.push({ type: 'codedecay.testId', description: ${JSON.stringify(testCase.id)} });`);
    appendGeneratedTestBody(lines, testCase, flowMap);
    lines.push("  });");
  }

  lines.push("});", "");
  return lines.join("\n");
}

function addGeneratedTestCase(tests: ProductGeneratedTestCase[], seen: Set<string>, test: ProductGeneratedTestCase): void {
  if (seen.has(test.id)) {
    return;
  }

  seen.add(test.id);
  tests.push(test);
}

function appendGeneratedTestBody(lines: string[], testCase: ProductGeneratedTestCase, flowMap: ProductFlowMap): void {
  const page = findFlowPageForTest(flowMap, testCase.pageUrl);
  const pagePath = new URL(testCase.pageUrl).pathname || "/";

  if (testCase.kind === "route-load") {
    lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
    lines.push("    await expect(page.locator('body')).toBeVisible();");
    if (page?.title) {
      lines.push(`    await expect(page).toHaveTitle(${regexLiteralForText(page.title)});`);
    }
    return;
  }

  if (testCase.kind === "link-navigation") {
    const link = page?.links.find((candidate) => candidate.href === testCase.targetUrl || candidate.selector === testCase.selector);
    lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
    lines.push(`    await ${locatorForInteractiveElement("link", link?.text ?? testCase.title, testCase.selector)}.click();`);
    lines.push(`    await expect(page).toHaveURL(productUrl(${JSON.stringify(new URL(testCase.targetUrl ?? testCase.pageUrl).pathname || "/")}));`);
    return;
  }

  if (testCase.kind === "input-state") {
    const element = page?.interactiveElements.find((candidate) => candidate.selector === testCase.selector);
    const sampleValue = sampleValueForInput(element?.inputType, element?.name);
    lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
    lines.push(`    const field = ${locatorForInteractiveElement("input", element?.name ?? testCase.title, testCase.selector)};`);
    lines.push(`    await field.fill(${JSON.stringify(sampleValue)});`);
    lines.push(`    await expect(field).toHaveValue(${JSON.stringify(sampleValue)});`);
    return;
  }

  const element = page?.interactiveElements.find((candidate) => candidate.selector === testCase.selector);
  lines.push(`    await page.goto(productUrl(${JSON.stringify(pagePath)}));`);
  lines.push(`    await expect(${locatorForInteractiveElement("form", element?.name ?? testCase.title, testCase.selector)}).toBeVisible();`);
}

function locatorForInteractiveElement(kind: "link" | "input" | "form", name: string, selector: string | undefined): string {
  const safeName = normalizeWhitespace(name);
  const fallback = selector ? `.or(page.locator(${JSON.stringify(selector)}))` : "";
  if (kind === "link") {
    return `page.getByRole('link', { name: ${regexLiteralForText(safeName)} }).first()${fallback}`;
  }

  if (kind === "input") {
    return `page.getByLabel(${regexLiteralForText(safeName)}).or(page.getByPlaceholder(${regexLiteralForText(safeName)}))${fallback}.first()`;
  }

  return selector ? `page.locator(${JSON.stringify(selector)}).first()` : `page.getByRole('form', { name: ${regexLiteralForText(safeName)} }).first()`;
}

function findFlowPageForTest(flowMap: ProductFlowMap, url: string): ProductFlowPage | undefined {
  return flowMap.pages.find((page) => page.url === url);
}

function safeInputType(inputType: string | undefined): boolean {
  return ["text", "email", "search", "tel", "url", "password", undefined].includes(inputType);
}

function sampleValueForInput(inputType: string | undefined, name: string | undefined): string {
  const normalized = `${inputType ?? ""} ${name ?? ""}`.toLowerCase();
  if (normalized.includes("email")) {
    return "codedecay@example.com";
  }

  if (normalized.includes("phone") || normalized.includes("tel")) {
    return "5550100";
  }

  if (normalized.includes("url")) {
    return "https://example.com";
  }

  if (normalized.includes("password")) {
    return "CodeDecayTest123!";
  }

  return "CodeDecay test";
}
