#!/usr/bin/env bash
# Remove local setup state generated by setup.local.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_DIR="$SCRIPT_DIR/local"

rm -rf "$LOCAL_DIR"
echo "Removed CodeDecay local setup state."
echo "No database, containers, or seeded services are used by this repo."
