import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { createLowRiskRepo, createTempDir, getFreePort, installFakePlaywright, run, startDemoApiServer, startDemoAppServer, startHealthServer, writeApiProductTargetConfig, writeDemoOpenApiSchema, writeFile, writeManualApiProductTargetConfig, writeProductTargetConfig } from "./helpers";

describe("codedecay generated UI product test CLI contract", () => {
  it("generates reviewable Playwright tests from a product flow map", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const result = await run(["product", "--explore", "--generate-tests", "--max-pages", "5", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const sourcePath = join(repo, ".codedecay/local/generated-tests/web/product.generated.spec.ts");
      const manifestPath = join(repo, ".codedecay/local/generated-tests/web/manifest.json");
      const source = readFileSync(sourcePath, "utf8");
      const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedTests).toMatchObject({
        status: "passed",
        sourcePath: ".codedecay/local/generated-tests/web/product.generated.spec.ts",
        manifestPath: ".codedecay/local/generated-tests/web/manifest.json"
      });
      expect(report.targets[0].generatedTests.tests.length).toBeGreaterThanOrEqual(3);
      expect(report.safety.generatedTestsRan).toBe(false);
      expect(source).toContain("@generated by CodeDecay");
      expect(source).toContain("getByRole('link'");
      expect(source).toContain("getByLabel");
      expect(manifest).toMatchObject({
        schemaVersion: 1,
        reviewRequired: true,
        sourceFlowMapPath: ".codedecay/local/product-flow-maps/web/flow-map.json",
        testSourcePath: ".codedecay/local/generated-tests/web/product.generated.spec.ts"
      });
      expect(manifest.tests.length).toBeGreaterThanOrEqual(3);
      expect(existsSync(join(repo, "tests/e2e/codedecay-product.spec.ts"))).toBe(false);
    } finally {
      await server.close();
    }
  });

  it("runs generated Playwright tests through the project-local Playwright CLI", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const result = await run(["product", "--explore", "--generate-tests", "--run-generated-tests", "--max-pages", "5", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedTestRun).toMatchObject({
        status: "passed",
        failed: 0,
        skipped: 0
      });
      expect(report.targets[0].generatedTestRun.passed).toBeGreaterThanOrEqual(3);
      expect(report.targets[0].generatedTestRun.command).toContain("node_modules/playwright/cli.js");
      expect(report.safety.generatedTestsRan).toBe(true);
    } finally {
      await server.close();
    }
  });

  it("runs reviewed generated tests without overwriting local edits", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const generated = await run(["product", "--explore", "--generate-tests", "--max-pages", "5", "--format", "json"], repo);
      expect(generated.exitCode).toBe(0);

      const sourcePath = ".codedecay/local/generated-tests/web/product.generated.spec.ts";
      const reviewedSource = `${readFileSync(join(repo, sourcePath), "utf8")}\n// reviewed local edit\n`;
      writeFile(repo, sourcePath, reviewedSource);

      const result = await run(["product", "--run-generated-tests", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedTests.notes).toContain("Loaded existing generated tests without regenerating source.");
      expect(readFileSync(join(repo, sourcePath), "utf8")).toContain("// reviewed local edit");
    } finally {
      await server.close();
    }
  });

  it("reruns a single generated test by test id", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const generated = await run(["product", "--explore", "--generate-tests", "--max-pages", "5", "--format", "json"], repo);
      expect(generated.exitCode).toBe(0);
      const generatedReport = JSON.parse(generated.stdout);
      const testId = generatedReport.targets[0].generatedTests.tests[0].id;

      const result = await run(["product", "--run-generated-tests", "--test-id", testId, "--format", "json"], repo);
      const report = JSON.parse(result.stdout);

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedTestRun).toMatchObject({
        status: "passed",
        passed: 1,
        failed: 0
      });
      expect(report.targets[0].generatedTestRun.command).toContain("--grep");
    } finally {
      await server.close();
    }
  });

  it("reports generated test failures with source, failing step, and rerun command", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeFile(repo, "fail-generated-tests.txt", "yes\n");
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const result = await run(["product", "--explore", "--generate-tests", "--run-generated-tests", "--max-pages", "5", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const failure = report.targets[0].generatedTestRun.failures[0];

      expect(result.exitCode).toBe(1);
      expect(report.targets[0].status).toBe("failed");
      expect(report.targets[0].generatedTestRun).toMatchObject({
        status: "failed",
        failed: 1
      });
      expect(failure).toMatchObject({
        failingStep: expect.stringContaining("Run generated test"),
        testSourcePath: ".codedecay/local/generated-tests/web/product.generated.spec.ts"
      });
      expect(failure.rerunCommand).toContain("npx codedecay product --target web --run-generated-tests --test-id ");
      expect(failure.rerunCommand).toContain(" --format markdown");
      expect(failure.error).toContain("Forced generated test failure");
      expect(failure.testSource).toContain("@generated by CodeDecay");
      expect(failure.testSource).toContain("test.describe");

      const markdown = await run(["product", "--generate-tests", "--run-generated-tests", "--format", "markdown"], repo);
      expect(markdown.exitCode).toBe(1);
      expect(markdown.stdout).toContain("Failing step:");
      expect(markdown.stdout).toContain("Repeat evidence:");
      expect(markdown.stdout).toContain("Rerun: `npx codedecay product --target web --run-generated-tests --test-id ");
      expect(markdown.stdout).toContain("```ts");
      expect(markdown.stdout).toContain("@generated by CodeDecay");
    } finally {
      await server.close();
    }
  });

  it("records repeat evidence when a generated test passes on targeted rerun", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeFile(repo, "flaky-generated-tests.txt", "yes\n");
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const result = await run(["product", "--explore", "--generate-tests", "--run-generated-tests", "--max-pages", "5", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const failure = report.targets[0].generatedTestRun.failures[0];

      expect(result.exitCode).toBe(1);
      expect(failure.error).toContain("Flaky generated test failure");
      expect(failure.retryEvidence).toMatchObject({
        attempts: 2,
        passed: 1,
        failed: 1,
        conclusion: "passed-on-rerun"
      });
    } finally {
      await server.close();
    }
  });

  it("gates product failures by selected classification", async () => {
    const server = await startDemoAppServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeFile(repo, "fail-generated-tests.txt", "yes\n");
    writeProductTargetConfig(repo, {
      baseUrl: server.origin,
      allowCommands: true
    });

    try {
      const reportOnly = await run(
        [
          "product",
          "--explore",
          "--generate-tests",
          "--run-generated-tests",
          "--max-pages",
          "5",
          "--fail-on-classification",
          "likely-flaky",
          "--format",
          "json"
        ],
        repo
      );
      const strictGate = await run(
        [
          "product",
          "--explore",
          "--generate-tests",
          "--run-generated-tests",
          "--max-pages",
          "5",
          "--fail-on-classification",
          "confirmed-regression",
          "--format",
          "json"
        ],
        repo
      );

      expect(reportOnly.exitCode).toBe(0);
      expect(JSON.parse(reportOnly.stdout).summary.status).toBe("failed");
      expect(strictGate.exitCode).toBe(1);
    } finally {
      await server.close();
    }
  });
});
