import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { createLowRiskRepo, createTempDir, getFreePort, installFakePlaywright, run, startDemoApiServer, startDemoAppServer, startHealthServer, writeApiProductTargetConfig, writeDemoOpenApiSchema, writeFile, writeManualApiProductTargetConfig, writeProductTargetConfig } from "./helpers";

describe("codedecay generated API product test CLI contract", () => {
  it("generates reviewable API tests from a configured OpenAPI schema", async () => {
    const server = await startDemoApiServer();
    const repo = createLowRiskRepo();
    writeDemoOpenApiSchema(repo);
    writeApiProductTargetConfig(repo, {
      baseUrl: server.origin,
      healthCheck: server.healthUrl,
      allowCommands: false
    });

    try {
      const result = await run(["product", "--target", "api", "--generate-api-tests", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const sourcePath = join(repo, ".codedecay/local/generated-api-tests/api/api.generated.spec.ts");
      const manifestPath = join(repo, ".codedecay/local/generated-api-tests/api/manifest.json");
      const source = readFileSync(sourcePath, "utf8");
      const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedApiTests).toMatchObject({
        status: "passed",
        sourcePath: ".codedecay/local/generated-api-tests/api/api.generated.spec.ts",
        manifestPath: ".codedecay/local/generated-api-tests/api/manifest.json"
      });
      expect(report.targets[0].generatedApiTests.tests).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            kind: "api-operation",
            method: "GET",
            operationPath: "/api/users",
            expectedStatuses: [200, 401]
          }),
          expect.objectContaining({
            method: "POST",
            destructive: true
          })
        ])
      );
      expect(source).toContain("@generated by CodeDecay");
      expect(source).toContain("CodeDecay generated API regression tests");
      expect(source).toContain('test.skip("POST /api/users returns a documented status"');
      expect(manifest).toMatchObject({
        schemaVersion: 1,
        reviewRequired: true,
        sourceOpenApiSchemaPath: "docs/openapi.yaml",
        testSourcePath: ".codedecay/local/generated-api-tests/api/api.generated.spec.ts",
        promoteByCopyingTo: "tests/api/codedecay-api.spec.ts"
      });
      expect(existsSync(join(repo, "tests/api/codedecay-api.spec.ts"))).toBe(false);
    } finally {
      await server.close();
    }
  });

  it("prioritizes generated product checks from repo memory", async () => {
    const server = await startDemoApiServer();
    const repo = createLowRiskRepo();
    writeDemoOpenApiSchema(repo);
    writeApiProductTargetConfig(repo, {
      baseUrl: server.origin,
      healthCheck: server.healthUrl,
      allowCommands: false
    });
    writeFile(
      repo,
      ".codedecay/memory.json",
      JSON.stringify(
        {
          version: 1,
          flows: [
            {
              name: "User detail flow",
              files: ["README.md"],
              productPaths: ["/api/users/{id}"],
              checks: ["user detail stays readable after docs-linked changes"]
            }
          ],
          regressions: [
            {
              title: "Users list 500",
              description: "A previous generated product check caught a users list 500.",
              areas: ["api"],
              productPaths: ["/api/users"],
              severity: "high"
            }
          ]
        },
        null,
        2
      )
    );

    try {
      const result = await run(["product", "--target", "api", "--generate-api-tests", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const tests = report.targets[0].generatedApiTests.tests;

      expect(result.exitCode).toBe(0);
      expect(tests).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            method: "GET",
            operationPath: "/api/users",
            priority: "high"
          }),
          expect.objectContaining({
            method: "GET",
            operationPath: "/api/users/1",
            priority: "high"
          })
        ])
      );
    } finally {
      await server.close();
    }
  });

  it("generates API tests from manually configured endpoint lists", async () => {
    const server = await startDemoApiServer();
    const repo = createLowRiskRepo();
    writeManualApiProductTargetConfig(repo, {
      baseUrl: server.origin,
      healthCheck: server.healthUrl,
      allowCommands: false
    });

    try {
      const result = await run(["product", "--target", "api", "--generate-api-tests", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const source = readFileSync(join(repo, ".codedecay/local/generated-api-tests/api/api.generated.spec.ts"), "utf8");
      const manifest = JSON.parse(readFileSync(join(repo, ".codedecay/local/generated-api-tests/api/manifest.json"), "utf8"));

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedApiTests.tests).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            id: "list-users",
            method: "GET",
            operationPath: "/api/users",
            expectedStatuses: [200]
          }),
          expect.objectContaining({
            method: "POST",
            requestBody: {
              email: "codedecay@example.com"
            },
            destructive: true
          })
        ])
      );
      expect(source).toContain("x-codedecay-scenario");
      expect(source).toContain("codedecay@example.com");
      expect(manifest).toMatchObject({
        sourceApiEndpoints: "productTesting.targets.api.apiEndpoints",
        testSourcePath: ".codedecay/local/generated-api-tests/api/api.generated.spec.ts"
      });
    } finally {
      await server.close();
    }
  });

  it("runs generated API tests through the project-local Playwright CLI", async () => {
    const server = await startDemoApiServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeDemoOpenApiSchema(repo);
    writeApiProductTargetConfig(repo, {
      baseUrl: server.origin,
      healthCheck: server.healthUrl,
      allowCommands: true
    });

    try {
      const result = await run(["product", "--target", "api", "--generate-api-tests", "--run-generated-api-tests", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);

      expect(result.exitCode).toBe(0);
      expect(report.targets[0].generatedApiTestRun).toMatchObject({
        status: "passed",
        failed: 0
      });
      expect(report.targets[0].generatedApiTestRun.passed).toBeGreaterThanOrEqual(2);
      expect(report.targets[0].generatedApiTestRun.command).toContain("node_modules/playwright/cli.js");
      expect(report.safety.generatedTestsRan).toBe(true);
    } finally {
      await server.close();
    }
  });

  it("reports generated API test failures with request evidence and rerun command", async () => {
    const server = await startDemoApiServer();
    const repo = createLowRiskRepo();
    installFakePlaywright(repo);
    writeFile(repo, "fail-generated-tests.txt", "yes\n");
    writeDemoOpenApiSchema(repo);
    writeApiProductTargetConfig(repo, {
      baseUrl: server.origin,
      healthCheck: server.healthUrl,
      allowCommands: true
    });

    try {
      const result = await run(["product", "--target", "api", "--generate-api-tests", "--run-generated-api-tests", "--format", "json"], repo);
      const report = JSON.parse(result.stdout);
      const failure = report.targets[0].generatedApiTestRun.failures[0];

      expect(result.exitCode).toBe(1);
      expect(report.targets[0].status).toBe("failed");
      expect(failure).toMatchObject({
        testSourcePath: ".codedecay/local/generated-api-tests/api/api.generated.spec.ts",
        request: {
          method: "GET"
        }
      });
      expect(failure.rerunCommand).toContain("npx codedecay product --target api --run-generated-api-tests --test-id ");
      expect(failure.rerunCommand).toContain(" --format markdown");
      expect(failure.request.url).toContain(`${server.origin}/api/users`);
      expect(failure.expected).toContain("documented statuses");
      expect(failure.actual).toContain("Forced generated test failure");
      expect(failure.impactedFiles).toContain("README.md");

      const markdown = await run(["product", "--target", "api", "--generate-api-tests", "--run-generated-api-tests", "--format", "markdown"], repo);
      expect(markdown.exitCode).toBe(1);
      expect(markdown.stdout).toContain("API failure:");
      expect(markdown.stdout).toContain(`Request: GET \`${failure.request.url}\``);
      expect(markdown.stdout).toContain("Rerun: `npx codedecay product --target api --run-generated-api-tests --test-id ");
    } finally {
      await server.close();
    }
  });
});
