export const orderedPages = [
  "index.md",
  "getting-started.md",
  "editor-workflows.md",
  "trend-snapshots.md",
  "github-action.md",
  "configuration.md",
  "redteam.md",
  "agent.md",
  "mcp.md",
  "github-app.md",
  "execution.md",
  "differential.md",
  "product-testing.md",
  "test-audit.md",
  "evals/first-efficacy-report.md",
  "tool-adapters.md",
  "skills.md",
  "memory.md",
  "llm-providers.md",
  "sample-reports/index.md",
  "sample-reports/sample-report.md",
  "scoring.md",
  "benchmark-corpus.md",
  "deployment-surfaces.md",
  "release-policy.md",
  "research.md",
  "releasing.md",
  "proposals/framework-aware-impact-map.md",
  "rfcs/0001-agent-agnostic-redteam-harness.md",
  "launch-post.md"
];

export const sectionTitles = new Map([
  ["index.md", "Overview"],
  ["getting-started.md", "Guides"],
  ["editor-workflows.md", "Guides"],
  ["trend-snapshots.md", "Guides"],
  ["github-action.md", "Guides"],
  ["configuration.md", "Guides"],
  ["redteam.md", "Guides"],
  ["agent.md", "Guides"],
  ["mcp.md", "Guides"],
  ["github-app.md", "Guides"],
  ["execution.md", "Guides"],
  ["differential.md", "Guides"],
  ["product-testing.md", "Guides"],
  ["test-audit.md", "Guides"],
  ["evals/first-efficacy-report.md", "Guides"],
  ["tool-adapters.md", "Guides"],
  ["skills.md", "Guides"],
  ["memory.md", "Guides"],
  ["llm-providers.md", "Guides"],
  ["sample-reports/index.md", "Samples"],
  ["sample-reports/sample-report.md", "Samples"],
  ["scoring.md", "Reference"],
  ["benchmark-corpus.md", "Reference"],
  ["deployment-surfaces.md", "Reference"],
  ["release-policy.md", "Reference"],
  ["research.md", "Reference"],
  ["releasing.md", "Reference"],
  ["proposals/framework-aware-impact-map.md", "Roadmap"],
  ["rfcs/0001-agent-agnostic-redteam-harness.md", "Roadmap"],
  ["launch-post.md", "Misc"]
]);

export const titleOverrides = new Map([
  ["index.md", "CodeDecay Docs"],
  ["sample-reports/sample-report.md", "Sample CodeDecay Markdown Report"]
]);
