#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const workDir = join(repoRoot, ".codedecay/local/hackathon-demo-video");
const publicDir = join(repoRoot, "judge-lab/public/demo");
const metadataDir = join(repoRoot, "docs/hackathon/demo/generated");
const videoPath = join(publicDir, "codedecay-codex-repair.mp4");
const captionsPath = join(publicDir, "codedecay-codex-repair.vtt");
const posterPath = join(publicDir, "codedecay-codex-repair-poster.png");
const metadataPath = join(metadataDir, "video-metadata.json");
const screenshotPath = resolve(process.argv[2] ?? "/tmp/codedecay-demo-assets/judge-lab.png");
const release = "v0.4.1";
const riskyFixture = "36a38500031f8330654c5e04c0d49062f09314ec";
const baseFixture = "f042684b1d7c306adf5b85c6ca43c6f9e14ab5cc";

const scenes = [
  {
    kicker: "01 / THE FALSE GREEN",
    title: "A PASSING TEST IS NOT PROOF.",
    badge: "REAL CODEX RUN",
    hold: 13,
    lines: [
      ["command", "$ npm test"],
      ["good", "✓ keeps the authenticated user id"],
      ["good", "1 test passed"],
      ["bad", "But anonymous GET /api/users → 200 admin"],
    ],
    narration:
      "A coding agent changed an admin API. Its narrow session test still passed, but an anonymous caller could now receive an admin-shaped response. This is the false confidence CodeDecay is built to challenge.",
  },
  {
    kicker: "02 / REPRODUCIBLE INPUT",
    title: "ONE FIXTURE. TWO COMMITS. NO DEPENDENCIES.",
    badge: release,
    hold: 14,
    lines: [
      ["muted", `base  ${baseFixture.slice(0, 12)}`],
      ["bad", `risky ${riskyFixture.slice(0, 12)}`],
      ["muted", "Codex CLI 0.145.0 · workspace-write sandbox"],
      ["muted", "Edited for time; one session, output preserved"],
    ],
    narration:
      "The demo uses a dependency-free, two-commit repository generated by the public setup script. This is one genuine Codex session in a workspace-write sandbox. Private paths are redacted, and only waiting and repetitive output are cut.",
  },
  {
    kicker: "03 / CODEDECAY HANDOFF",
    title: "START WITH GROUNDED EVIDENCE.",
    badge: "TOOL EVIDENCE",
    hold: 15,
    lines: [
      ["command", "$ codedecay ai --base HEAD^ --with-checks"],
      ["bad", "HIGH · merge risk 78 / 100"],
      ["warn", "1 missing-test finding"],
      ["good", "configured unit check passed"],
      ["muted", "Changed: src/auth/session.js, src/routes/users.js"],
    ],
    narration:
      "Before Codex edits anything, CodeDecay packages the diff, repository memory, the API review skill, and the approved unit check. It reports high risk, two changed security-sensitive files, and missing real-path proof, even though the configured unit test passed.",
  },
  {
    kicker: "04 / CODEX PLAN",
    title: "PROVE THE USER-FACING FAILURE FIRST.",
    badge: "CODEX",
    hold: 14,
    lines: [
      ["good", "1. Inspect auth, route, server, tests, and config"],
      ["good", "2. Reproduce anonymous and authorized behavior"],
      ["good", "3. Add endpoint proof before the fix"],
      ["good", "4. Repair, run checks, revalidate, self-review"],
    ],
    narration:
      "Codex reads the bundle and the repository skill, then makes a four-step plan: inspect the real path, reproduce both caller states, add a red endpoint test before changing production code, and only then repair and revalidate.",
  },
  {
    kicker: "05 / RED EVIDENCE",
    title: "THE REAL NODE HTTP PATH FAILS.",
    badge: "EXPECTED FAILURE",
    hold: 16,
    lines: [
      ["command", "$ npm run probe:anonymous"],
      ["bad", "expected 401 · actual 200"],
      ["bad", '[{"id":"anonymous","role":"admin"}]'],
      ["command", "$ node --test test/integration/users-api.test.js"],
      ["bad", "anonymous: 200 !== 401"],
      ["good", "authorized: 200 ✓"],
    ],
    narration:
      "The live probe reaches the actual Node HTTP server and returns two hundred with an anonymous admin. Codex adds an endpoint test without mocking the route. Before the repair, the anonymous assertion fails two hundred versus four oh one, while the authorized case remains green.",
  },
  {
    kicker: "06 / REPAIR",
    title: "FAIL CLOSED AT BOTH BOUNDARIES.",
    badge: "CODEX EDIT",
    hold: 15,
    lines: [
      ["bad", "- missing auth → anonymous admin session"],
      ["good", "+ missing auth → null"],
      ["bad", "- route always returns 200"],
      ["good", "+ no session → 401 unauthorized"],
      ["good", "+ test:api added to approved checks"],
    ],
    narration:
      "Codex restores fail-closed behavior at both layers. Missing authorization no longer creates a session, the users route denies a missing session, and the real endpoint test becomes a named, explicitly configured CodeDecay check.",
  },
  {
    kicker: "07 / VERIFIED CHECKS",
    title: "GREEN NOW MEANS MORE.",
    badge: "TOOL EVIDENCE",
    hold: 15,
    lines: [
      ["good", "✓ npm test · 1 / 1"],
      ["good", "✓ npm run test:api · 2 / 2"],
      ["good", '✓ anonymous probe · 401 {"error":"unauthorized"}'],
      ["good", "✓ git diff --check"],
      ["muted", "CodeDecay executed both allowlisted commands"],
    ],
    narration:
      "After the repair, the original unit test passes, both anonymous and authorized endpoint cases pass, the live probe returns four oh one with an unauthorized body, and the diff is clean. CodeDecay independently executes both allowlisted checks again.",
  },
  {
    kicker: "08 / REVALIDATION",
    title: "FIXED DOES NOT MEAN ZERO RISK.",
    badge: "HONEST RESULT",
    hold: 17,
    lines: [
      ["good", "Missing-test findings: 1 → 0"],
      ["good", "Finding lifecycle: 1 fixed"],
      ["warn", "4 auth/API context findings confirmed"],
      ["warn", "Post-fix risk: HIGH · 80 / 100"],
      ["muted", "Proof still static without a coverage artifact"],
    ],
    narration:
      "Revalidation marks the missing-nearby-test finding fixed, and missing-test findings drop to zero. But CodeDecay still reports high risk at eighty, confirms four auth and API context signals, and says proof remains static without a runtime coverage artifact.",
  },
  {
    kicker: "09 / CODEX SELF-REVIEW",
    title: "SEPARATE FACTS FROM SUGGESTIONS.",
    badge: "LIMITATIONS",
    hold: 18,
    lines: [
      ["good", "Verified: HTTP 401, authorized 200, two checks passed"],
      ["warn", "Suggested: JWT hardening, fuzzing, mutation testing"],
      ["bad", "Remaining: any non-empty token is still admin"],
      ["muted", "No zero-risk claim · no hidden model call · no telemetry"],
    ],
    narration:
      "Codex self-reviews the result. The HTTP behavior and checks are tool evidence. JWT hardening, fuzzing, and mutation testing are suggestions, not executed proof. The fixture still accepts any non-empty token as admin, so neither Codex nor CodeDecay claims zero risk.",
  },
  {
    kicker: "10 / TRY IT",
    title: "FIND WHAT YOUR CODING AGENT MISSED.",
    badge: `${release} · BUILDING EVALS`,
    hold: 18,
    screenshot: true,
    lines: [
      ["good", "Public Judge Lab · no login"],
      ["good", "Benchmark · 23 / 23 planted issues · 2.22% FP"],
      ["muted", "github.com/SubmuxHQ/CodeDecay"],
      ["muted", "npm: @submuxhq/codedecay"],
      ["muted", `fixture ${riskyFixture.slice(0, 12)} · transcript + cuts public`],
    ],
    narration:
      "Try the public Judge Lab with no login, inspect the open-source repository and the twenty-three of twenty-three planted-issue benchmark, or install at submux h q slash codedecay. The tagged release is version zero point four point one. The exact fixture, transcript, commands, captions, and timing-cut disclosure are public.",
  },
];

rmSync(workDir, { recursive: true, force: true });
mkdirSync(workDir, { recursive: true });
mkdirSync(publicDir, { recursive: true });
mkdirSync(metadataDir, { recursive: true });

const playwrightModule = pathToFileURL(
  join(repoRoot, "judge-lab/node_modules/playwright/index.mjs"),
).href;
const { chromium } = await import(playwrightModule);
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const screenshotData = readFileSync(screenshotPath).toString("base64");
const durations = [];

for (const [index, scene] of scenes.entries()) {
  const id = String(index + 1).padStart(2, "0");
  const frame = join(workDir, `${id}.png`);
  const audio = join(workDir, `${id}.aiff`);
  const segment = join(workDir, `${id}.mp4`);
  await page.setContent(renderScene(scene, index, scenes.length, screenshotData));
  await page.screenshot({ path: frame });
  if (index === 0) copyFileSync(frame, posterPath);
  run("say", ["-v", "Samantha", "-r", "188", "-o", audio, scene.narration]);
  const audioDuration = Number.parseFloat(probe(audio, "format=duration"));
  const duration = Math.max(scene.hold, audioDuration + 0.75);
  const fadeOut = Math.max(0, duration - 0.4);
  run("ffmpeg", [
    "-hide_banner",
    "-loglevel",
    "error",
    "-y",
    "-loop",
    "1",
    "-i",
    frame,
    "-i",
    audio,
    "-filter_complex",
    `[0:v]fade=t=in:st=0:d=0.35,fade=t=out:st=${fadeOut.toFixed(3)}:d=0.35,format=yuv420p[v];[1:a]apad=pad_dur=${Math.max(0, duration - audioDuration).toFixed(3)}[a]`,
    "-map",
    "[v]",
    "-map",
    "[a]",
    "-t",
    duration.toFixed(3),
    "-r",
    "30",
    "-c:v",
    "libx264",
    "-preset",
    "medium",
    "-crf",
    "20",
    "-c:a",
    "aac",
    "-b:a",
    "160k",
    segment,
  ]);
  durations.push(duration);
}

await browser.close();
const concatPath = join(workDir, "concat.txt");
writeFileSync(
  concatPath,
  scenes.map((_, index) => `file '${String(index + 1).padStart(2, "0")}.mp4'`).join("\n"),
);
run("ffmpeg", [
  "-hide_banner",
  "-loglevel",
  "error",
  "-y",
  "-f",
  "concat",
  "-safe",
  "0",
  "-i",
  concatPath,
  "-c",
  "copy",
  "-movflags",
  "+faststart",
  videoPath,
]);

writeFileSync(captionsPath, renderVtt(scenes, durations), "utf8");
const duration = Number.parseFloat(probe(videoPath, "format=duration"));
const width = Number.parseInt(probe(videoPath, "stream=width", "v:0"), 10);
const height = Number.parseInt(probe(videoPath, "stream=height", "v:0"), 10);
const audioCodec = probe(videoPath, "stream=codec_name", "a:0");
if (duration > 180 || width < 1920 || height < 1080 || !audioCodec) {
  throw new Error(`Video verification failed: ${duration}s, ${width}x${height}, audio=${audioCodec}`);
}

writeFileSync(
  metadataPath,
  `${JSON.stringify(
    {
      release,
      baseFixture,
      riskyFixture,
      durationSeconds: Number(duration.toFixed(3)),
      dimensions: `${width}x${height}`,
      audioCodec,
      captions: "/demo/codedecay-codex-repair.vtt",
      poster: "/demo/codedecay-codex-repair-poster.png",
      editedForTime: true,
      cuts: "Waiting and repetitive report output only; command order and results preserved.",
    },
    null,
    2,
  )}\n`,
  "utf8",
);
process.stdout.write(`Video written to ${videoPath} (${duration.toFixed(2)}s)\n`);

function run(command, args) {
  const result = spawnSync(command, args, { cwd: workDir, encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(`${command} failed:\n${result.stderr || result.stdout}`);
  }
}

function probe(path, field, selector) {
  const args = ["-v", "error"];
  if (selector) args.push("-select_streams", selector);
  args.push("-show_entries", field, "-of", "default=noprint_wrappers=1:nokey=1", path);
  const result = spawnSync("ffprobe", args, { encoding: "utf8" });
  if (result.status !== 0) throw new Error(`ffprobe failed for ${path}: ${result.stderr}`);
  return result.stdout.trim();
}

function renderVtt(items, sceneDurations) {
  let cursor = 0;
  const cues = items.map((scene, index) => {
    const start = cursor;
    cursor += sceneDurations[index];
    return `${timestamp(start)} --> ${timestamp(cursor)}\n${scene.narration}`;
  });
  return `WEBVTT\n\n${cues.join("\n\n")}\n`;
}

function timestamp(seconds) {
  const milliseconds = Math.round(seconds * 1000);
  const hours = Math.floor(milliseconds / 3_600_000);
  const minutes = Math.floor((milliseconds % 3_600_000) / 60_000);
  const secs = Math.floor((milliseconds % 60_000) / 1000);
  const ms = milliseconds % 1000;
  return [hours, minutes, secs]
    .map((value) => String(value).padStart(2, "0"))
    .join(":")
    .concat(`.${String(ms).padStart(3, "0")}`);
}

function renderScene(scene, index, total, screenshotData) {
  const lineHtml = scene.lines
    .map(([kind, text]) => `<div class="line ${kind}">${escapeHtml(text)}</div>`)
    .join("");
  const imageHtml = scene.screenshot
    ? `<div class="shot"><img alt="" src="data:image/png;base64,${screenshotData}"></div><div class="shot-lines">${lineHtml}</div>`
    : "";
  return `<!doctype html>
<html><head><style>
*{box-sizing:border-box}body{margin:0;width:1920px;height:1080px;overflow:hidden;background:#090908;color:#f3efe5;font-family:Arial,"Helvetica Neue",sans-serif}
.grain{position:absolute;inset:0;background:radial-gradient(circle at 78% 20%,rgba(255,107,44,.09),transparent 34%),linear-gradient(125deg,transparent 0 55%,rgba(255,255,255,.015) 55% 56%,transparent 56%);pointer-events:none}
.top{height:86px;border-bottom:1px solid #2d2c26;display:flex;align-items:center;justify-content:space-between;padding:0 78px;font:700 18px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em}
.brand{display:flex;align-items:center;gap:16px}.mark{display:grid;place-items:center;width:42px;height:42px;background:#ff6b2c;color:#130b07;font-size:13px;font-weight:900}.badge{border:1px solid #48463c;color:#ff9668;padding:11px 14px;font-size:13px}
.wrap{display:grid;grid-template-columns:1.02fr .98fr;gap:70px;padding:82px 92px 72px;height:912px;align-items:center}
.kicker{color:#ff6b2c;font:800 16px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.15em}.title{font-size:74px;line-height:.94;letter-spacing:-.055em;margin:28px 0 38px;max-width:850px}.context{color:#aaa598;font:16px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace}.terminal{border:1px solid #48463c;background:#10100e;box-shadow:20px 20px 0 rgba(255,107,44,.08);padding:0;min-height:500px;display:flex;flex-direction:column;justify-content:center}.bar{position:absolute;margin-top:-500px;width:820px;height:52px;border-bottom:1px solid #2d2c26;color:#8f8a7e;padding:17px 24px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.lines{padding:76px 44px 38px}.line{font:22px/1.72 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap}.command{color:#f3efe5}.good{color:#6ee7a2}.bad{color:#ff604f}.warn{color:#f6c453}.muted{color:#aaa598}.shot{position:absolute;right:86px;top:150px;width:720px;border:1px solid #48463c;box-shadow:20px 20px 0 rgba(255,107,44,.08);overflow:hidden}.shot img{display:block;width:100%;filter:saturate(.9) contrast(1.03)}.shot-lines{position:absolute;right:86px;bottom:82px;width:720px;background:#10100e;border:1px solid #48463c;padding:20px 24px}.shot-lines .line{font-size:15px;line-height:1.55}.wrap:has(.shot) .terminal{opacity:.08}.progress{position:absolute;left:0;right:0;bottom:0;height:42px;border-top:1px solid #2d2c26;display:flex;align-items:center;padding:0 78px;gap:22px;color:#8f8a7e;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.track{height:3px;flex:1;background:#2d2c26}.fill{height:100%;background:#ff6b2c;width:${((index + 1) / total) * 100}%}
</style></head><body><div class="grain"></div>
<header class="top"><div class="brand"><span class="mark">CD</span><span>CODEDECAY × CODEX</span></div><span class="badge">${escapeHtml(scene.badge)}</span></header>
<main class="wrap"><section><div class="kicker">${escapeHtml(scene.kicker)}</div><h1 class="title">${escapeHtml(scene.title)}</h1><p class="context">Building Evals · public reproducibility pack<br>Tool evidence ≠ agent suggestion ≠ safety guarantee</p></section><section class="terminal"><div class="bar">● ● ● &nbsp; GENUINE SESSION / SANITIZED</div><div class="lines">${lineHtml}</div></section>${imageHtml}</main>
<footer class="progress"><span>${String(index + 1).padStart(2, "0")} / ${String(total).padStart(2, "0")}</span><div class="track"><div class="fill"></div></div><span>Find what your coding agent missed before merge.</span></footer>
</body></html>`;
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
